### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by KoolPal** [studioslashnl/woocommerce-manually-add-review#1]
@joriswvanrijn Any plans to update this plugin?

**Comment by joriswvanrijn** [comment]
@KoolPal unfortunately not, since I’m not using it anymore on active websites. Is it broken in new WP versions?

**Comment by KoolPal** [comment]
@joriswvanrijn Oh it's a pity. This plugin looked like a promising start.

Yes there were some errors but if you are not actively using it, I would not want to bother you.

Are you using some other plugin instead? If yes, please guide.

Thanks

**Comment by joriswvanrijn** [comment]
@KoolPal I'm not using any other plugin right now. I hope you'll find a suitable solution! I do think Woocommerce has a feature now to import/export reviews, maybe that will help!

https://woocommerce.com/document/import-and-export-of-woocommerce-product-reviews/

**Comment by joriswvanrijn** [comment]
@KoolPal I'm not using any other plugin right now. I hope you'll find a suitable solution! I do think Woocommerce has a feature now to import/export reviews, maybe that will help!

https://woocommerce.com/document/import-and-export-of-woocommerce-product-reviews/

Good luck!
